const easyWords = [
    "apple", "banana", "cherry", "dog", "elephant", "fish", "grape", "house", "ice", "jump",
    "king", "lion", "monkey", "nut", "orange", "pear", "queen", "rabbit", "sun", "tree",
    "umbrella", "van", "whale", "yellow", "zebra", "bat", "car", "door", "egg", "frog",
    "goat", "hat", "island", "jelly", "kite", "leaf", "mouse", "night", "octopus", "pen",
    "quiz", "rose", "star", "toy", "under", "vase", "water", "yogurt", "zip", "baby", "cat",
    "easy", "fast", "good", "home", "look", "make", "nice", "open", "park", "quick", "rain",
    "soft", "time", "up", "very", "wish", "zoo", "art", "bear", "ball", "blue", "book",
    "candy", "dance", "egg", "flower", "game", "green", "hand", "jolly", "lemon", "light",
    "mirror", "nap", "orange", "pen", "quiz", "red", "sea", "tree", "vine", "wind", "yard",
    "always", "bake", "cool", "dear", "eat", "fall", "go", "hello", "jump", "keep", "look",
    "make", "new", "open", "quiet", "run", "see", "top", "use", "walk", "yes", "zebra", "bread",
    "come", "deer", "hill", "idea", "join", "keep", "love", "move", "night", "over", "pink",
    "queen", "red", "shoe", "tall", "view", "win", "year", "art", "ball", "fun", "green",
    "hug", "iron", "kiss", "lake", "mail", "near", "one", "play", "rain", "shop", "time",
    "vast", "wild", "box", "color", "dream", "frog", "goat", "hot", "jump", "snow", "top",
    "visit", "web", "animal", "bird", "dog", "egg", "fire", "goose", "help", "ice", "love",
    "mom", "now", "park", "rain", "sun", "view", "yellow", "all", "card", "ear", "fire",
    "good", "hero", "joy", "king", "laugh", "laugh", "make", "new", "open", "quack", "run",
    "sun", "top", "view", "wax", "zip", "ask", "bat", "car", "dog", "eat", "fire", "high",
    "ice", "joy", "kite", "leaf", "man", "no", "pen", "ship", "time", "up", "vast", "win",
    "yellow", "zip", "all", "bird", "deer", "eat", "fun", "game", "good", "help", "ice",
    "jump", "kite", "lake", "make", "near", "one", "pet", "quiz", "run", "snow", "top",
    "vast", "wind", "win", "xray", "yellow", "zebra", "art", "boy", "cool", "dog", "eat",
    "frog", "game", "help", "iron", "joy", "kite", "love", "man", "near", "pet", "quit",
    "red", "small", "tall", "under", "view", "win", "zoo", "apple", "bake", "cup", "dream",
    "gum", "help", "ice", "jump", "kite", "love", "mom", "no", "open", "play", "quick",
    "red", "ship", "time", "up", "vast", "win", "yellow", "zip", "apple", "bake", "cup",
    "dream", "fast", "gum", "help", "ice", "jump", "kite", "love", "mom", "no", "one",
    "play", "quick", "red", "ship", "time", "up", "vast", "win", "yellow", "zip", "art",
    "boy", "cool", "dog", "eat", "frog", "game", "help", "iron", "joy", "kite", "love",
    "man", "near", "one", "pet", "quit", "red", "small", "tall", "under", "view", "win",
    "xray", "yellow", "zoo", "apple", "bake", "cup", "dream", "fast", "gum", "help",
    "ice", "jump", "kite", "love", "mom", "no", "open", "play", "quick", "red", "ship",
    "time", "up", "vast", "win", "yellow", "zip"
];

const expertWords = [
    "abandon", "absurd", "acquire", "allegro", "ambitious", "ancient", "anxiety", "apparent", "barrier", "bizarre",
    "brilliant", "brother", "cabinet", "captive", "chronic", "compel", "conscious", "courage", "counter", "culture",
    "delight", "demonstrate", "diploma", "disaster", "dominate", "emerge", "empower", "envious", "factor", "famine",
    "ferocious", "fluent", "forecast", "genuine", "harmony", "hospital", "iconic", "impact", "inspire", "jungle",
    "legitimate", "logical", "mature", "migrate", "mischief", "momentum", "natural", "neatly", "obvious", "obsolete",
    "outcome", "praise", "popular", "reluctant", "rescue", "retain", "sincere", "skillful", "solution", "stamina",
    "symbolic", "tangible", "tension", "thriving", "unfold", "unique", "unveil", "vacuum", "venture", "vivid",
    "wonder", "zodiac", "advocate", "adverse", "advance", "aggregate", "ambush", "analog", "cattle", "climate",
    "compete", "compose", "credible", "defend", "eagle", "elaborate", "eloquent", "enlist", "examine", "explode",
    "flinch", "formula", "generate", "hypothesize", "intact", "isolate", "innovate", "jargon", "lattice", "medal",
    "optimize", "originate", "parade", "protest", "progress", "reverse", "secure", "serene", "sophisticate", "tragedy",
    "tolerate", "unite", "uphold", "vanguard", "verify", "wander", "yield", "accept", "assemble", "benefit",
    "bravely", "capture", "clarify", "commute", "diverse", "expose", "flavor", "habitual", "impose", "indicate",
    "justify", "lean", "motivate", "portray", "relent", "revere", "restore", "satisfy", "subdue", "succeed"
];

const masterWords = [
    "aberration", "alchemy", "ambivalence", "analytical", "belligerent", "cacophony", "capitulate", "caustic",
    "concatenate", "debilitate", "defenestration", "effervescent", "egregious", "emaciated", "ephemeral",
    "epitome", "equanimity", "esoteric", "facetious", "fallacious", "fortuitous", "garrulous", "gregarious",
    "haphazard", "hermetic", "holistic", "iconoclast", "immutable", "impetuous", "inexorable", "inscrutable",
    "intrepid", "juxtapose", "kaleidoscope", "laconic", "lamentable", "libertine", "ludicrous", "magnanimous",
    "maelstrom", "melancholy", "meritorious", "nefarious", "obfuscate", "perfidious", "perspicacious", "precocious",
    "quixotic", "ravenous", "recalcitrant", "recondite", "repugnant", "resilient", "rhetoric", "scintillating",
    "sedulous", "serendipity", "sophomoric", "spurious", "supercilious", "sycophant", "taciturn", "transitory",
    "trenchant", "unabashed", "ubiquitous", "vehement", "vicarious", "vindicate", "volition", "wanderlust",
    "wretched", "abstruse", "adulation", "altruism", "ambidextrous", "anomalous", "antagonistic", "apocryphal",
    "argumentative", "ascendancy", "belligerence", "bifurcate", "calamity", "censorious", "chimerical", "coercive",
    "compunction", "conducive", "contrive", "cryptic", "defiant", "demur", "dichotomy", "dissonance", "dogmatic",
    "efficacious", "equivocate", "erratic", "exculpate", "fervent", "finesse", "flabbergast", "gargantuan",
    "grandiloquent", "harangue", "hedonistic", "heuristic", "hubris", "immutable", "inexorable", "ingenious",
    "insidious", "intangible", "intermittent", "intransigent", "judicious", "labyrinthine", "licentious",
    "magnificent", "malevolent", "meticulous", "misanthrope", "narcissistic", "oblivion", "opulent", "ornate",
    "perfunctory", "prodigal", "quandary", "reprehensible", "reticent", "rhetoric", "salient", "seditious",
    "serene", "singular", "spontaneous", "subterfuge", "surreptitious", "sycophantic", "traverse", "turbulent",
    "unconventional", "vindictive", "volatile", "wanton", "whimsical", "abrogate", "benign", "capricious",
    "circumspect", "coherent", "compelling", "concurrent", "congenial", "conscientious", "desolate", "dormant",
    "effulgent", "empathetic", "equanimous", "erudite", "exquisite", "feral", "flagrant", "foment", "gnostic",
    "hyperbole", "implication", "infallible", "incisive", "intransigent", "jovial", "kaleidoscopic", "luminous",
    "meritorious", "nebulous", "paradox", "pedantic", "precipitous", "propinquity", "prurient", "punctilious",
    "qualitative", "quintessential", "recalcitrant", "resilient", "rigorous", "salubrious", "serendipitous",
    "solipsistic", "superlative", "sublime", "transcend", "unscrupulous", "vagabond", "venal", "veracity",
    "vituperative", "warranted", "zealous", "zephyr", "altruistic", "beseech", "candor", "confluence", "dissension",
    "egregious", "facetious", "gesticulate", "harbinger", "infinitesimal", "loquacious", "nefarious", "philanthropic",
    "prodigious", "punitive", "ravenous", "repudiation", "sagacious", "spurious", "temerity", "tranquil", "unabated"
];


export { easyWords, expertWords, masterWords };